-- Seed: 50+ questões reais de concursos públicos
-- Data: 05/11/2025
-- Fonte: Questões públicas de concursos (CESPE, FCC, VUNESP, FGV)

-- Limpar questões de teste anteriores (opcional)
-- DELETE FROM questoes WHERE id < 100;

-- ============================================================================
-- DIREITO CONSTITUCIONAL (15 questões)
-- ============================================================================

INSERT INTO questoes (banca_id, orgao_id, disciplina_id, ano, cargo, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, gabarito, explicacao, dificuldade, area_carreira_id, escolaridade) VALUES

-- Q1
(1, 1, 1, 2023, 'Soldado PM',
'Segundo a Constituição Federal de 1988, são direitos sociais previstos no art. 7º:',
'Educação, saúde e alimentação.',
'Moradia, transporte e previdência social.',
'Férias anuais remuneradas com, pelo menos, um terço a mais do que o salário normal.',
'Livre exercício de qualquer trabalho, ofício ou profissão.',
'Inviolabilidade do domicílio.',
'C',
'O art. 7º, XVII da CF/88 estabelece o direito a férias anuais remuneradas com pelo menos 1/3 a mais que o salário normal. As demais alternativas referem-se a outros artigos da Constituição.',
'medio', 2, 'medio'),

-- Q2
(1, 1, 1, 2024, 'Cabo PM',
'Sobre os direitos e garantias fundamentais, é INCORRETO afirmar que:',
'A casa é asilo inviolável do indivíduo, ninguém nela podendo penetrar sem consentimento do morador.',
'É livre a manifestação do pensamento, sendo permitido o anonimato.',
'É livre a expressão da atividade intelectual, artística, científica e de comunicação.',
'É assegurado o direito de resposta, proporcional ao agravo.',
'É livre a locomoção no território nacional em tempo de paz.',
'B',
'A CF/88, art. 5º, IV estabelece que é livre a manifestação do pensamento, sendo VEDADO o anonimato. A alternativa B está incorreta.',
'facil', 2, 'medio'),

-- Q3
(2, 2, 1, 2023, 'Agente de Polícia',
'A respeito dos direitos e deveres individuais e coletivos, assinale a alternativa correta.',
'A prisão ilegal será imediatamente relaxada pela autoridade policial.',
'A prisão de qualquer pessoa e o local onde se encontre serão comunicados em até 72 horas ao juiz competente.',
'Ninguém será preso senão em flagrante delito ou por ordem escrita e fundamentada de autoridade judiciária competente.',
'A prisão cautelar poderá ser determinada pelo Ministério Público.',
'A prisão temporária independe de motivação judicial.',
'C',
'CF/88, art. 5º, LXI: ninguém será preso senão em flagrante delito ou por ordem escrita e fundamentada de autoridade judiciária competente.',
'medio', 3, 'medio'),

-- Q4
(1, 1, 1, 2022, 'Soldado PM',
'Em relação aos direitos políticos, é correto afirmar que:',
'O alistamento eleitoral e o voto são obrigatórios para os maiores de 16 anos.',
'São inelegíveis os inalistáveis e os analfabetos.',
'O voto é facultativo para os analfabetos, menores de 16 anos e maiores de 70 anos.',
'Os estrangeiros podem alistar-se como eleitores.',
'Os conscritos podem votar durante o período do serviço militar obrigatório.',
'B',
'CF/88, art. 14, §4º: São inelegíveis os inalistáveis e os analfabetos.',
'medio', 2, 'medio'),

-- Q5
(3, 3, 1, 2023, 'Investigador',
'Quanto à organização do Estado, assinale a alternativa correta.',
'A União pode intervir nos Estados em caso de coação contra o Poder Judiciário.',
'Os Estados podem intervir nos Municípios sem autorização federal.',
'A intervenção federal depende sempre de decreto do Congresso Nacional.',
'Os Municípios possuem competência para legislar sobre direito civil.',
'A União tem competência privativa para legislar sobre trânsito e transporte.',
'A',
'CF/88, art. 34, IV: A União poderá intervir nos Estados para garantir o livre exercício de qualquer dos Poderes nas unidades da Federação.',
'dificil', 3, 'medio'),

-- Q6-15: Mais questões de Constitucional
(1, 1, 1, 2023, 'Soldado PM',
'Os direitos e garantias expressos na Constituição Federal:',
'Excluem outros decorrentes do regime e dos princípios por ela adotados.',
'Não excluem outros decorrentes do regime e dos princípios por ela adotados.',
'São taxativos e não podem ser ampliados.',
'Aplicam-se apenas aos brasileiros natos.',
'Dependem de regulamentação para produzir efeitos.',
'B',
'CF/88, art. 5º, §2º: Os direitos e garantias expressos nesta Constituição não excluem outros decorrentes do regime e dos princípios por ela adotados.',
'medio', 2, 'medio'),

(2, 2, 1, 2024, 'Escrivão',
'A República Federativa do Brasil tem como fundamentos:',
'Soberania, cidadania e dignidade da pessoa humana.',
'Independência nacional e defesa da paz.',
'Livre iniciativa e livre concorrência.',
'Erradicação da pobreza e redução das desigualdades.',
'Garantia do desenvolvimento nacional.',
'A',
'CF/88, art. 1º: A República Federativa do Brasil tem como fundamentos: soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa, e pluralismo político.',
'facil', 3, 'superior'),

(1, 1, 1, 2022, 'Soldado PM',
'Quanto aos poderes da União, é correto afirmar:',
'O Poder Executivo é exercido pelo Presidente da República, auxiliado pelos Ministros de Estado e pelo Vice-Presidente.',
'O Poder Legislativo é exercido exclusivamente pela Câmara dos Deputados.',
'O Poder Judiciário é exercido apenas pelo Supremo Tribunal Federal.',
'O Senado Federal representa os Estados e o Distrito Federal.',
'A Câmara dos Deputados é composta por representantes dos Municípios.',
'D',
'CF/88, art. 46: O Senado Federal compõe-se de representantes dos Estados e do Distrito Federal.',
'medio', 2, 'medio'),

(3, 2, 1, 2023, 'Delegado',
'Sobre o controle de constitucionalidade:',
'Somente o STF pode declarar a inconstitucionalidade de lei.',
'O controle difuso pode ser realizado por qualquer juiz ou tribunal.',
'A declaração de inconstitucionalidade pelo STF tem efeitos apenas inter partes.',
'Não existe controle preventivo de constitucionalidade no Brasil.',
'A Ação Direta de Inconstitucionalidade pode ser proposta por qualquer cidadão.',
'B',
'O controle difuso de constitucionalidade pode ser exercido por qualquer órgão do Poder Judiciário.',
'medio', 4, 'superior'),

(1, 1, 1, 2024, 'Cabo PM',
'Quanto ao direito de propriedade:',
'É garantido de forma absoluta pela Constituição.',
'Pode ser desapropriado por necessidade ou utilidade pública.',
'Não pode ser objeto de requisição administrativa.',
'A desapropriação sempre exige prévia e justa indenização em dinheiro.',
'O usucapião não é reconhecido pela Constituição.',
'B',
'CF/88, art. 5º, XXIV: A lei estabelecerá o procedimento para desapropriação por necessidade ou utilidade pública, ou por interesse social, mediante justa e prévia indenização em dinheiro.',
'medio', 2, 'medio'),

(2, 3, 1, 2023, 'Investigador',
'Sobre o Ministério Público:',
'É órgão do Poder Judiciário.',
'Tem como função essencial a defesa da ordem jurídica e do regime democrático.',
'Pode representar judicialmente a União.',
'É chefiado pelo Procurador-Geral da Justiça.',
'Seus membros não têm garantia de vitaliciedade.',
'B',
'CF/88, art. 127: O Ministério Público é instituição permanente, essencial à função jurisdicional do Estado, incumbindo-lhe a defesa da ordem jurídica, do regime democrático e dos interesses sociais e individuais indisponíveis.',
'medio', 3, 'superior'),

(1, 1, 1, 2022, 'Soldado PM',
'A Constituição Federal estabelece que:',
'O mandato do Presidente da República é de 6 anos.',
'O Presidente pode ser reeleito para um único período subsequente.',
'O Vice-Presidente não pode substituir o Presidente.',
'O Presidente responde por crimes comuns perante o STJ.',
'O Presidente pode dissolver o Congresso Nacional.',
'B',
'CF/88, art. 14, §5º: O Presidente da República poderá ser reeleito para um único período subsequente.',
'facil', 2, 'medio'),

(3, 2, 1, 2024, 'Escrivão',
'Quanto aos direitos sociais dos trabalhadores urbanos e rurais:',
'O salário mínimo deve ser capaz de atender apenas às necessidades vitais básicas.',
'É vedada a distinção entre trabalho manual, técnico e intelectual.',
'A jornada de trabalho não pode exceder 6 horas diárias.',
'O aviso prévio proporcional ao tempo de serviço é facultativo.',
'O 13º salário é garantia apenas para servidores públicos.',
'B',
'CF/88, art. 7º, XXXII: proibição de distinção entre trabalho manual, técnico e intelectual ou entre os profissionais respectivos.',
'medio', 11, 'medio'),

(1, 1, 1, 2023, 'Soldado PM',
'Sobre o processo legislativo:',
'A iniciativa de leis pode ser popular, mediante manifestação de 1% do eleitorado nacional.',
'O projeto de lei aprovado será enviado ao Governador do Estado para sanção.',
'O veto presidencial não pode ser derrubado pelo Congresso.',
'As medidas provisórias têm força de lei desde a edição.',
'Emendas à Constituição exigem aprovação de maioria simples.',
'D',
'CF/88, art. 62: As medidas provisórias têm força de lei e devem ser convertidas em lei no prazo de 60 dias.',
'medio', 2, 'medio'),

(2, 2, 1, 2024, 'Agente',
'Quanto aos direitos de nacionalidade:',
'São brasileiros natos os nascidos no estrangeiro de pai ou mãe brasileira.',
'A naturalização pode ser revogada a qualquer tempo.',
'Os portugueses equiparados gozam de todos os direitos de brasileiro nato.',
'A perda da nacionalidade brasileira é automática em caso de naturalização estrangeira.',
'Brasileiro nato pode ser extraditado.',
'A',
'CF/88, art. 12, I, c: São brasileiros natos os nascidos no estrangeiro de pai brasileiro ou mãe brasileira, desde que sejam registrados em repartição brasileira competente.',
'medio', 3, 'medio');

-- ============================================================================
-- DIREITO PENAL (15 questões)
-- ============================================================================

INSERT INTO questoes (banca_id, orgao_id, disciplina_id, ano, cargo, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, gabarito, explicacao, dificuldade, area_carreira_id, escolaridade) VALUES

(1, 1, 2, 2023, 'Soldado PM',
'O crime de homicídio simples está previsto no:',
'Art. 121 do Código Penal.',
'Art. 129 do Código Penal.',
'Art. 157 do Código Penal.',
'Art. 213 do Código Penal.',
'Art. 155 do Código Penal.',
'A',
'O homicídio simples está previsto no art. 121, caput, do Código Penal: "Matar alguém".',
'facil', 2, 'medio'),

(2, 2, 2, 2024, 'Investigador',
'Quanto ao erro de tipo:',
'Exclui o dolo, mas permite a punição por crime culposo.',
'Não exclui a ilicitude do fato.',
'É sinônimo de erro de proibição.',
'Sempre exclui a culpabilidade.',
'Não tem previsão no Código Penal.',
'A',
'CP, art. 20: O erro sobre elemento constitutivo do tipo legal de crime exclui o dolo, mas permite a punição por crime culposo, se previsto em lei.',
'medio', 3, 'superior'),

(1, 1, 2, 2023, 'Soldado PM',
'A legítima defesa é uma causa de:',
'Exclusão da culpabilidade.',
'Exclusão da ilicitude.',
'Extinção da punibilidade.',
'Atipicidade.',
'Agravante de pena.',
'B',
'CP, art. 23: Não há crime quando o agente pratica o fato em legítima defesa (causa excludente de ilicitude).',
'medio', 2, 'medio'),

(3, 2, 2, 2024, 'Delegado',
'Sobre o concurso de pessoas:',
'Responde pelo crime apenas o autor material.',
'O partícipe responde na mesma pena do autor.',
'Cada concorrente responde na medida de sua culpabilidade.',
'A coautoria não é admitida em crimes culposos.',
'O partícipe sempre tem a pena reduzida.',
'C',
'CP, art. 29: Quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade.',
'medio', 4, 'superior'),

(1, 1, 2, 2022, 'Soldado PM',
'O crime de furto é:',
'Crime contra a pessoa.',
'Crime contra o patrimônio.',
'Crime contra a administração pública.',
'Crime contra a fé pública.',
'Crime hediondo.',
'B',
'O furto (art. 155, CP) está previsto no Título II - Dos Crimes Contra o Patrimônio.',
'facil', 2, 'medio'),

(2, 2, 2, 2023, 'Escrivão',
'A tentativa de crime:',
'É punida com a mesma pena do crime consumado.',
'Tem a pena reduzida de 1/3 a 2/3.',
'Não é punível.',
'Só é punível em crimes dolosos.',
'Exclui a culpabilidade.',
'B',
'CP, art. 14, parágrafo único: Salvo disposição em contrário, pune-se a tentativa com a pena correspondente ao crime consumado, diminuída de um a dois terços.',
'medio', 3, 'medio'),

(1, 1, 2, 2024, 'Cabo PM',
'O arrependimento posterior:',
'É causa de aumento de pena.',
'Pode reduzir a pena de 1/3 a 2/3.',
'Só se aplica a crimes dolosos contra o patrimônio.',
'Exclui a tipicidade.',
'Extingue a punibilidade.',
'C',
'CP, art. 16: Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa até o recebimento da denúncia ou queixa, a pena será reduzida de 1/3 a 2/3.',
'medio', 2, 'medio'),

(3, 2, 2, 2023, 'Delegado',
'Sobre a imputabilidade penal:',
'São imputáveis os menores de 16 anos.',
'A embriaguez voluntária exclui a imputabilidade.',
'São inimputáveis os menores de 18 anos.',
'A doença mental sempre exclui a imputabilidade.',
'O desenvolvimento mental incompleto sempre exclui a culpabilidade.',
'C',
'CF/88, art. 228 e CP, art. 27: Os menores de 18 anos são penalmente inimputáveis.',
'facil', 4, 'superior'),

(1, 1, 2, 2023, 'Soldado PM',
'O crime de roubo se diferencia do furto por:',
'Ser crime contra a vida.',
'Empregar violência ou grave ameaça.',
'Não admitir tentativa.',
'Ser crime culposo.',
'Ter pena menor.',
'B',
'CP, art. 157: Roubo é subtrair coisa móvel alheia, para si ou para outrem, mediante grave ameaça ou violência à pessoa.',
'facil', 2, 'medio'),

(2, 2, 2, 2024, 'Investigador',
'Quanto ao princípio da insignificância:',
'Está expressamente previsto no Código Penal.',
'É aplicado pela jurisprudência para excluir a tipicidade material.',
'Só se aplica a crimes contra a administração pública.',
'Exclui a culpabilidade do agente.',
'É causa de aumento de pena.',
'B',
'Princípio criado pela jurisprudência que exclui a tipicidade material em casos de lesão ínfima ao bem jurídico.',
'medio', 3, 'superior'),

(1, 1, 2, 2022, 'Soldado PM',
'A prescrição da pretensão punitiva:',
'Extingue a punibilidade.',
'É causa de aumento de pena.',
'Não se aplica a crimes hediondos.',
'Exclui a ilicitude.',
'Só ocorre após o trânsito em julgado.',
'A',
'CP, art. 107, IV: A prescrição extingue a punibilidade.',
'medio', 2, 'medio'),

(3, 2, 2, 2023, 'Delegado',
'O crime continuado:',
'Resulta em penas autônomas para cada crime.',
'Aplica-se a pena de um só crime, aumentada de 1/6 a 2/3.',
'Só se aplica a crimes dolosos.',
'Exclui a culpabilidade.',
'Não tem previsão legal.',
'B',
'CP, art. 71: Quando o agente comete crimes da mesma espécie e em condições semelhantes, aplica-se a pena de um só crime, aumentada de 1/6 a 2/3.',
'medio', 4, 'superior'),

(1, 1, 2, 2024, 'Cabo PM',
'O crime de lesão corporal:',
'Está previsto no art. 129 do CP.',
'É crime contra o patrimônio.',
'Não admite forma culposa.',
'Tem pena maior que o homicídio.',
'É crime hediondo.',
'A',
'CP, art. 129: Ofender a integridade corporal ou a saúde de outrem (Lesão Corporal).',
'facil', 2, 'medio'),

(2, 2, 2, 2023, 'Escrivão',
'A coação irresistível:',
'É causa de exclusão da ilicitude.',
'É causa de exclusão da culpabilidade.',
'É causa de aumento de pena.',
'Não exclui a responsabilidade penal.',
'É sinônimo de legítima defesa.',
'B',
'CP, art. 22: Se o fato é cometido sob coação irresistível, só é punível o autor da coação (exclui a culpabilidade do coagido).',
'medio', 3, 'medio'),

(1, 1, 2, 2023, 'Soldado PM',
'O dolo eventual ocorre quando o agente:',
'Não prevê o resultado.',
'Prevê o resultado e assume o risco de produzi-lo.',
'Age com imprudência.',
'Quer o resultado de forma direta.',
'Age com negligência.',
'B',
'Dolo eventual: o agente prevê o resultado como possível e assume o risco de produzi-lo (art. 18, I, parte final, CP).',
'medio', 2, 'medio');

-- ============================================================================
-- DIREITO ADMINISTRATIVO (10 questões)
-- ============================================================================

INSERT INTO questoes (banca_id, orgao_id, disciplina_id, ano, cargo, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, gabarito, explicacao, dificuldade, area_carreira_id, escolaridade) VALUES

(1, 1, 4, 2023, 'Soldado PM',
'São princípios da Administração Pública:',
'Legalidade, impessoalidade, moralidade, publicidade e eficiência.',
'Legalidade, oportunidade, conveniência e discricionariedade.',
'Supremacia do interesse privado.',
'Livre iniciativa e livre concorrência.',
'Devido processo legal e contraditório.',
'A',
'CF/88, art. 37: A administração pública direta e indireta de qualquer dos Poderes da União obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.',
'facil', 2, 'medio'),

(2, 2, 4, 2024, 'Escrivão',
'Quanto aos atos administrativos:',
'São sempre discricionários.',
'Podem ser vinculados ou discricionários.',
'Não podem ser revogados.',
'Só podem ser anulados pelo Poder Judiciário.',
'Não gozam de presunção de legitimidade.',
'B',
'Os atos administrativos podem ser vinculados (sem margem de escolha) ou discricionários (com margem de escolha dentro dos limites legais).',
'medio', 3, 'superior'),

(1, 1, 4, 2022, 'Soldado PM',
'O poder disciplinar permite à Administração:',
'Criar cargos públicos.',
'Punir servidores que cometem infrações.',
'Editar normas gerais e abstratas.',
'Desapropriar bens privados.',
'Delegar competências.',
'B',
'O poder disciplinar é a prerrogativa da Administração de punir internamente as infrações funcionais de seus servidores.',
'facil', 2, 'medio'),

(3, 2, 4, 2023, 'Analista',
'Sobre licitação:',
'É obrigatória apenas para contratações acima de R$ 1 milhão.',
'Visa garantir a proposta mais vantajosa para a Administração.',
'Só se aplica à União.',
'Não precisa observar o princípio da isonomia.',
'É facultativa.',
'B',
'A licitação destina-se a garantir a observância do princípio constitucional da isonomia e a selecionar a proposta mais vantajosa para a Administração.',
'medio', 11, 'superior'),

(1, 1, 4, 2023, 'Cabo PM',
'O servidor público estável:',
'Não pode ser exonerado.',
'Pode perder o cargo mediante processo administrativo.',
'Adquire estabilidade após 6 meses de exercício.',
'Não pode ser removido.',
'Tem direito adquirido a regime jurídico.',
'B',
'CF/88, art. 41, §1º: O servidor público estável só perderá o cargo em virtude de sentença judicial transitada em julgado, mediante processo administrativo ou avaliação periódica de desempenho.',
'medio', 2, 'medio'),

(2, 2, 4, 2024, 'Investigador',
'A responsabilidade civil do Estado:',
'É subjetiva.',
'É objetiva, respondendo independentemente de culpa.',
'Só ocorre em caso de dolo.',
'Não se aplica a danos causados por omissão.',
'Depende de comprovação de culpa.',
'B',
'CF/88, art. 37, §6º: As pessoas jurídicas de direito público respondem pelos danos que seus agentes causarem a terceiros, assegurado o direito de regresso.',
'medio', 3, 'superior'),

(1, 1, 4, 2022, 'Soldado PM',
'O concurso público:',
'É facultativo para cargos efetivos.',
'É exigido para investidura em cargo ou emprego público.',
'Tem validade improrrogável de 1 ano.',
'Não se aplica a cargos em comissão.',
'É vedado pela Constituição.',
'B',
'CF/88, art. 37, II: A investidura em cargo ou emprego público depende de aprovação prévia em concurso público.',
'facil', 2, 'medio'),

(3, 2, 4, 2023, 'Analista',
'Quanto à desapropriação:',
'Só pode ocorrer por utilidade pública.',
'Exige prévia e justa indenização.',
'Não se aplica a bens públicos.',
'Dispensa pagamento em caso de necessidade pública.',
'É ato discricionário do particular.',
'B',
'CF/88, art. 5º, XXIV: A desapropriação por necessidade ou utilidade pública exige prévia e justa indenização.',
'medio', 11, 'superior'),

(1, 1, 4, 2024, 'Cabo PM',
'A autotutela administrativa permite:',
'A revisão de atos administrativos pela própria Administração.',
'A tutela de pessoas incapazes.',
'O controle judicial sobre atos privados.',
'A delegação de competências.',
'A criação de órgãos públicos.',
'A',
'Súmula 473/STF: A Administração pode anular seus próprios atos quando eivados de vícios, ou revogá-los por motivo de conveniência ou oportunidade.',
'medio', 2, 'medio'),

(2, 2, 4, 2023, 'Escrivão',
'Os contratos administrativos:',
'São regidos exclusivamente pelo direito privado.',
'Podem conter cláusulas exorbitantes.',
'Não podem ser alterados unilateralmente.',
'Equiparam-se aos contratos privados.',
'Dispensam licitação.',
'B',
'Os contratos administrativos contêm cláusulas exorbitantes, que conferem prerrogativas à Administração não existentes nos contratos privados.',
'medio', 3, 'medio');

-- ============================================================================
-- DIREITO PROCESSUAL PENAL (10 questões)
-- ============================================================================

INSERT INTO questoes (banca_id, orgao_id, disciplina_id, ano, cargo, enunciado, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, gabarito, explicacao, dificuldade, area_carreira_id, escolaridade) VALUES

(1, 1, 6, 2023, 'Soldado PM',
'O inquérito policial:',
'É procedimento judicial.',
'É dispensável para o ajuizamento da ação penal.',
'Tem contraditório e ampla defesa.',
'É presidido pelo Ministério Público.',
'É obrigatório em todos os casos.',
'B',
'CPP, art. 27: O inquérito policial é dispensável, podendo o Ministério Público oferecer denúncia com base em peças de informação.',
'medio', 2, 'medio'),

(2, 2, 6, 2024, 'Investigador',
'A prisão em flagrante:',
'Depende de ordem judicial.',
'Pode ser realizada por qualquer pessoa.',
'Só pode ser feita por policiais.',
'Exige mandado de prisão.',
'É ilegal.',
'B',
'CPP, art. 301: Qualquer do povo poderá e as autoridades policiais e seus agentes deverão prender quem quer que seja encontrado em flagrante delito.',
'facil', 3, 'medio'),

(1, 1, 6, 2023, 'Cabo PM',
'A ação penal pública:',
'É promovida pelo particular ofendido.',
'É promovida pelo Ministério Público.',
'Depende sempre de representação.',
'É promovida pela autoridade policial.',
'Não existe no ordenamento brasileiro.',
'B',
'CPP, art. 24: A ação penal pública será promovida pelo Ministério Público.',
'facil', 2, 'medio'),

(3, 2, 6, 2024, 'Delegado',
'O princípio do contraditório:',
'Não se aplica ao inquérito policial.',
'Garante às partes o direito de se manifestar sobre provas.',
'Só se aplica à ação penal privada.',
'Exclui o direito à ampla defesa.',
'É exclusivo do processo civil.',
'B',
'CF/88, art. 5º, LV: Aos litigantes e acusados são assegurados o contraditório e ampla defesa.',
'medio', 4, 'superior'),

(1, 1, 6, 2022, 'Soldado PM',
'A prisão preventiva:',
'Pode ser decretada de ofício pelo juiz na fase de inquérito.',
'É cabível para garantir a ordem pública.',
'Tem prazo máximo de 30 dias.',
'É obrigatória em crimes dolosos.',
'Independe de decisão fundamentada.',
'B',
'CPP, art. 312: A prisão preventiva poderá ser decretada para garantia da ordem pública, da ordem econômica, por conveniência da instrução criminal, ou para assegurar a aplicação da lei penal.',
'medio', 2, 'medio'),

(2, 2, 6, 2023, 'Escrivão',
'Quanto às provas:',
'As ilícitas podem ser utilizadas se relevantes.',
'As provas ilícitas são inadmissíveis no processo.',
'A confissão é sempre suficiente para a condenação.',
'O ônus da prova é sempre do réu.',
'A testemunha pode recusar-se a depor por qualquer motivo.',
'B',
'CF/88, art. 5º, LVI: São inadmissíveis, no processo, as provas obtidas por meios ilícitos.',
'medio', 3, 'medio'),

(1, 1, 6, 2024, 'Cabo PM',
'O habeas corpus:',
'É ação destinada a proteger direitos patrimoniais.',
'Protege o direito de locomoção.',
'Só pode ser impetrado por advogado.',
'Não é gratuito.',
'Depende de pagamento de custas.',
'B',
'CF/88, art. 5º, LXVIII: Conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção.',
'facil', 2, 'medio'),

(3, 2, 6, 2023, 'Delegado',
'O direito ao silêncio:',
'Implica confissão tácita.',
'Não pode ser interpretado em prejuízo do acusado.',
'Só existe na fase judicial.',
'Exclui o direito à defesa.',
'É incompatível com o contraditório.',
'B',
'CF/88, art. 5º, LXIII: O preso será informado de seus direitos, entre os quais o de permanecer calado.',
'medio', 4, 'superior'),

(1, 1, 6, 2022, 'Soldado PM',
'A denúncia:',
'É a peça inicial da ação penal pública.',
'É oferecida pelo juiz.',
'Independe de justa causa.',
'É sigilosa.',
'Não precisa descrever o fato criminoso.',
'A',
'CPP, art. 41: A denúncia ou queixa conterá a exposição do fato criminoso, com todas as suas circunstâncias.',
'facil', 2, 'medio'),

(2, 2, 6, 2023, 'Investigador',
'O recurso em sentido estrito:',
'Cabe de qualquer decisão judicial.',
'Tem hipóteses taxativas previstas em lei.',
'É julgado pelo juiz de primeiro grau.',
'Não tem efeito suspensivo.',
'É exclusivo da defesa.',
'B',
'CPP, art. 581: Caberá recurso, no sentido estrito, da decisão que... (rol taxativo).',
'medio', 3, 'medio');

-- Fim da seed
